Formatted shell files with shfmt

diff --git a/shell/bash/bin/_matrix_menu b/shell/bash/bin/_matrix_menu
--- a/shell/bash/bin/_matrix_menu
+++ b/shell/bash/bin/_matrix_menu
@@ -8,24 +8,24 @@
 
 # Full help message
 function matrix_menu_help() {
-    echo "A two-dimensional selection menu that the user can navigate" 1>&2
-    echo "with the arrow keys. Note that this is NOT the binary that should" 1>&2
-    echo "be called by the end user. They should use matrix_menu instead," 1>&2
-    echo "which is used the exact same way." 1>&2
-    matrix_menu_usage
+  echo "A two-dimensional selection menu that the user can navigate" 1>&2
+  echo "with the arrow keys. Note that this is NOT the binary that should" 1>&2
+  echo "be called by the end user. They should use matrix_menu instead," 1>&2
+  echo "which is used the exact same way." 1>&2
+  matrix_menu_usage
 }
 
 # Usage message
 function matrix_menu_usage() {
-    echo "Usage:" 1>&2
-    echo "This binary is used by calling matrix_menu and one or more --row (or -r) flags with the data" 1>&2
-    echo "for each row after each flag:" 1>&2
-    echo "    matrix_menu --row [row1_option1 [row1_option2 ...] --row [row2_option1 ...]], OR" 1>&2
-    echo "    matrix_menu -r [row1_option1 [row1_option2 ...] -r [row2_option1 ...]]" 1>&2
-    echo "Options:" 1>&2
-    echo "    --help | -h" 1>&2
-    echo "Print the help message" 1>&2
-    echo "NOTE: you may type 'q' to exit the menu and return to the terminal." 1>&2
+  echo "Usage:" 1>&2
+  echo "This binary is used by calling matrix_menu and one or more --row (or -r) flags with the data" 1>&2
+  echo "for each row after each flag:" 1>&2
+  echo "    matrix_menu --row [row1_option1 [row1_option2 ...] --row [row2_option1 ...]], OR" 1>&2
+  echo "    matrix_menu -r [row1_option1 [row1_option2 ...] -r [row2_option1 ...]]" 1>&2
+  echo "Options:" 1>&2
+  echo "    --help | -h" 1>&2
+  echo "Print the help message" 1>&2
+  echo "NOTE: you may type 'q' to exit the menu and return to the terminal." 1>&2
 }
 
 ################################################################################
@@ -35,32 +35,32 @@ function matrix_menu_usage() {
 ################################################################################
 
 # Exit the program if the user requests the help message:
-function exit_if_help_requested () {
-    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-        matrix_menu_help
-        exit 0
-    fi
+function exit_if_help_requested() {
+  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+    matrix_menu_help
+    exit 0
+  fi
 }
 
 # Exit the program if the user enters input incorrectly:
-function exit_if_input_incorrect () {
-    if [[ "$#" -eq 0 ]]; then
-        echoe "Need one or more rows of data"
-        matrix_menu_usage
-        exit 2
-    fi
+function exit_if_input_incorrect() {
+  if [[ "$#" -eq 0 ]]; then
+    echoe "Need one or more rows of data"
+    matrix_menu_usage
+    exit 2
+  fi
 
-    if [[ "$1" != "-r" && "$1" != "--row" ]]; then
-        echoe "Must provide one or more rows of data."
-        echo "Each row must be prefixed with either --row or -r."
-        exit 3
-    fi
+  if [[ "$1" != "-r" && "$1" != "--row" ]]; then
+    echoe "Must provide one or more rows of data."
+    echo "Each row must be prefixed with either --row or -r."
+    exit 3
+  fi
 }
 
 # make sure that cursor is returned to normal when script exits:
 function cleanup() {
-   tput cnorm
-   trap - EXIT
+  tput cnorm
+  trap - EXIT
 }
 trap cleanup EXIT
 
@@ -73,120 +73,120 @@ trap cleanup EXIT
 # Parse the user's input, determine the number of rows and columns, and
 # initialize the matrix with the user's data:
 function parse_input_and_init_matrix() {
-    local input="$@"
-    local token
-    local current_row=0
-    local current_column=0
-    for token in $input; do
-        if [[ "$token" == "-r" || "$token" == "--row" ]]; then
-            if [[ "$current_column" -ne 0 ]]; then
-                option_counts+=("$current_column")
-            fi
-            (( num_rows+=1 ))
-            (( current_row+=1 ))
-            current_column=0
-        else
-            (( current_column+=1 ))
-            if [[ "$current_column" -gt "$num_columns" ]]; then
-                (( num_columns+=1 ))
-            fi
-            matrix[$current_row,$current_column]="$token"
-        fi
-    done
-    option_counts+=("$current_column")
+  local input="$@"
+  local token
+  local current_row=0
+  local current_column=0
+  for token in $input; do
+    if [[ "$token" == "-r" || "$token" == "--row" ]]; then
+      if [[ "$current_column" -ne 0 ]]; then
+        option_counts+=("$current_column")
+      fi
+      ((num_rows += 1))
+      ((current_row += 1))
+      current_column=0
+    else
+      ((current_column += 1))
+      if [[ "$current_column" -gt "$num_columns" ]]; then
+        ((num_columns += 1))
+      fi
+      matrix[$current_row, $current_column]="$token"
+    fi
+  done
+  option_counts+=("$current_column")
 }
 
 # Initialize the display style variables
 function init_display_vars() {
-    option_spacer=5
-    column_spacer=$((${#num_rows}+1))
+  option_spacer=5
+  column_spacer=$((${#num_rows} + 1))
 }
 
 # Print the 2D matrix menu:
 function print_menu() {
-    local i j
-    for (( j = 1; j <= num_rows; j++ )) do
-        for (( i = 1; i <= num_columns; i++ )) do
-            if [[ $cursor_x == "$i" && $cursor_y == "$j" ]]; then
-                eval "printf \"%${option_spacer}s${color_reverse}%s${color_normal}\" \"\" \"\${matrix[$j,$i]}\""
-            else
-                eval "printf \"%${option_spacer}s%s\" \"\" \"\${matrix[$j,$i]}\""
-            fi
-        done
-        echo 1>&2
+  local i j
+  for ((j = 1; j <= num_rows; j++)); do
+    for ((i = 1; i <= num_columns; i++)); do
+      if [[ $cursor_x == "$i" && $cursor_y == "$j" ]]; then
+        eval "printf \"%${option_spacer}s${color_reverse}%s${color_normal}\" \"\" \"\${matrix[$j,$i]}\""
+      else
+        eval "printf \"%${option_spacer}s%s\" \"\" \"\${matrix[$j,$i]}\""
+      fi
     done
+    echo 1>&2
+  done
 }
 
 # Get the user's keyboard input and act accordingly:
 function get_user_input() {
-    local key k2
-    local lowest_y_index=$num_rows;
-    read -rsn 1 key
-    [[ "$key" == "$escape" ]] &&
+  local key k2
+  local lowest_y_index=$num_rows
+  read -rsn 1 key
+  [[ "$key" == "$escape" ]] &&
     {
-       read -rsn 2 k2
-       key="$key$k2"
+      read -rsn 2 k2
+      key="$key$k2"
     }
-    
-    if [[ ${option_counts[$num_rows]} -lt $lowest_y_index ]]; then
-        (( lowest_y_index-=1 ));
-    fi
 
-    case "$key" in
-        "$arrow_up")
-            if [[ $cursor_y -gt 1 && $cursor_x -le $(( ${option_counts[$cursor_y - 2]} )) ]]; then
-                (( cursor_y-=1 ))
-            elif [[ $cursor_y -eq 1 ]]; then
-                cursor_y=$num_rows;
-            fi
-            ;;
-        "$arrow_down")
-            if [[ $cursor_y -lt "$num_rows" && $cursor_x -le $(( ${option_counts[$cursor_y]} )) ]]; then
-                (( cursor_y+=1 ))
-            elif [[ $cursor_y -eq $num_rows ]]; then
-                cursor_y=1;
-            fi
-            ;;
-        "$arrow_right")
-            if [[ $cursor_x -lt $(( ${option_counts[$cursor_y - 1]} )) ]]; then
-                (( cursor_x+=1 ))
-            elif [[ $cursor_x -eq ${option_counts[$cursor_y - 1]} ]]; then
-                cursor_x=1;
-            fi
-            ;;
-        "$arrow_left")
-            if [[ $cursor_x -gt 1 ]]; then
-                (( cursor_x-=1 ))
-            elif [[ $cursor_x -eq 1 ]]; then
-                cursor_x=${option_counts[$cursor_y - 1]};
-            fi
-            ;;
-        "$newline")
-            end=true
-            made_selection=true
-            ;;
-        "q")
-            end=true
-            made_selection=false
-            ;;
-    esac
+  if [[ ${option_counts[$num_rows]} -lt $lowest_y_index ]]; then
+    ((lowest_y_index -= 1))
+  fi
+
+  case "$key" in
+  "$arrow_up")
+    if [[ $cursor_y -gt 1 && $cursor_x -le $((${option_counts[$cursor_y - 2]})) ]]; then
+      ((cursor_y -= 1))
+    elif [[ $cursor_y -eq 1 ]]; then
+      cursor_y=$num_rows
+    fi
+    ;;
+  "$arrow_down")
+    if [[ $cursor_y -lt "$num_rows" && $cursor_x -le $((${option_counts[$cursor_y]})) ]]; then
+      ((cursor_y += 1))
+    elif [[ $cursor_y -eq $num_rows ]]; then
+      cursor_y=1
+    fi
+    ;;
+  "$arrow_right")
+    if [[ $cursor_x -lt $((${option_counts[$cursor_y - 1]})) ]]; then
+      ((cursor_x += 1))
+    elif [[ $cursor_x -eq ${option_counts[$cursor_y - 1]} ]]; then
+      cursor_x=1
+    fi
+    ;;
+  "$arrow_left")
+    if [[ $cursor_x -gt 1 ]]; then
+      ((cursor_x -= 1))
+    elif [[ $cursor_x -eq 1 ]]; then
+      cursor_x=${option_counts[$cursor_y - 1]}
+    fi
+    ;;
+  "$newline")
+    end=true
+    made_selection=true
+    ;;
+  "q")
+    end=true
+    made_selection=false
+    ;;
+  esac
 }
 
 # Return the user's selected option (if they made a selection):
 function return_selection() {
-    if $made_selection; then
-        # Note that x and y are flipped here, since x increases as it moves to
-        # the left and y increases downward, with the origin at the top left
-        # corner of the matrix.
-        echo "${matrix[$cursor_y,$cursor_x]}"
-    fi
+  if $made_selection; then
+    # Note that x and y are flipped here, since x increases as it moves to
+    # the left and y increases downward, with the origin at the top left
+    # corner of the matrix.
+    echo "${matrix[$cursor_y, $cursor_x]}"
+  fi
 }
 
 # Used for printing errors:
-function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+function echoe() { echo -e "${RED}ERROR${NC}: $@" 1>&2; }
 
 # Used for printing warnings:
-function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
+function echow() { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2; }
 
 ################################################################################
 ##                                                                            ##
@@ -196,28 +196,28 @@ function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
 
 # Print the variable values
 function print_variables() {
-    echo "end: $end" 1>&2
-    echo "rum_rows: $num_rows" 1>&2
-    echo "num_columns: $num_columns" 1>&2
+  echo "end: $end" 1>&2
+  echo "rum_rows: $num_rows" 1>&2
+  echo "num_columns: $num_columns" 1>&2
 
-    local i j
-    echo -e "\nMenu:" 1>&2
-    printf "%${column_spacer}s" ''
-    for ((i=1; i<=num_columns; i++)) do
-        printf "%${option_spacer}s%${option_spacer}s" "" "$i"
+  local i j
+  echo -e "\nMenu:" 1>&2
+  printf "%${column_spacer}s" ''
+  for ((i = 1; i <= num_columns; i++)); do
+    printf "%${option_spacer}s%${option_spacer}s" "" "$i"
+  done
+  echo
+
+  for ((j = 1; j <= num_rows; j++)); do
+    printf "%${column_spacer}s" $j
+    for ((i = 1; i <= num_columns; i++)); do
+      printf "%${option_spacer}s%${option_spacer}s" "" "${matrix[$j, $i]}"
     done
     echo
+  done
 
-    for ((j=1; j<=num_rows; j++)) do
-        printf "%${column_spacer}s" $j
-        for ((i=1; i<=num_columns; i++)) do
-            printf "%${option_spacer}s%${option_spacer}s" "" "${matrix[$j,$i]}"
-        done
-        echo
-    done
-
-    echo -e "\nOption Counts:" 1>&2
-    echo "${option_counts[@]}" 1>&2
+  echo -e "\nOption Counts:" 1>&2
+  echo "${option_counts[@]}" 1>&2
 }
 
 ################################################################################
@@ -278,23 +278,23 @@ exit_if_input_incorrect "$@"
 
 # Begin capture stdout to stderr
 {
-    # Figure out option rows based on user input
-    parse_input_and_init_matrix "$@"
+  # Figure out option rows based on user input
+  parse_input_and_init_matrix "$@"
 
-    # Initialize the variables used to format the rows/columns of the menu
-    init_display_vars
+  # Initialize the variables used to format the rows/columns of the menu
+  init_display_vars
 
-    # Begin main program loop:
-    while ! $end; do
-        tput civis # hide cursor
-        print_menu
-        get_user_input
-        tput cuu "$num_rows"
-    done # End main program loop
+  # Begin main program loop:
+  while ! $end; do
+    tput civis # hide cursor
+    print_menu
+    get_user_input
+    tput cuu "$num_rows"
+  done # End main program loop
 
-    tput cud $(( num_rows - 1 ))
-    tput cnorm # unhide cursor
-    echo 1>&2
+  tput cud $((num_rows - 1))
+  tput cnorm # unhide cursor
+  echo 1>&2
 } >&2 # End capture stdout to stderr
 
 # Return the user's selection:
diff --git a/shell/bash/bin/arrutils b/shell/bash/bin/arrutils
--- a/shell/bash/bin/arrutils
+++ b/shell/bash/bin/arrutils
@@ -22,7 +22,6 @@
 #   --append <arr> <element> : appends element to the end of arr.
 #   --sort <arr> : quick sorts the array.
 
-
 ################################################################################
 ##                                                                            ##
 ##                           Supporting Functions                             ##
@@ -31,63 +30,64 @@
 
 # Usage message:
 function arrutils_usage() {
-    echo "Usage:" 1>&2
-    echo "  arrutils <options>" 1>&2
-    echo "Options:" 1>&2
-    echo "  --get-index-of arr element   : returns the index of the first occurance of element in" 1>&2
-    echo "                                 arr. Returns -1 if element does not exist in arr." 1>&2
-    echo "  --get-each-index-of arr element : returns an array containing each index where element occurs" 1>&2
-    echo "                                    withing arr. Will be empty if there are no occurances." 1>&2
-    echo "  --remove arr element : removes the first occurance of element in arr. Does nothing" 1>&2
-    echo "                                 element does not exist in arr." 1>&2
-    echo "  --remove-each arr element : removes each occurance of element within arr." 1>&2
-    echo "  --prepend arr element : places element at the beginning of arr" 1>&2
-    echo "  --append arr element : places element at the end of arr" 1>&2
-    echo "  --sort arr : performs a quick sort on the array" 1>&2
+  echo "Usage:" 1>&2
+  echo "  arrutils <options>" 1>&2
+  echo "Options:" 1>&2
+  echo "  --get-index-of arr element   : returns the index of the first occurance of element in" 1>&2
+  echo "                                 arr. Returns -1 if element does not exist in arr." 1>&2
+  echo "  --get-each-index-of arr element : returns an array containing each index where element occurs" 1>&2
+  echo "                                    withing arr. Will be empty if there are no occurances." 1>&2
+  echo "  --remove arr element : removes the first occurance of element in arr. Does nothing" 1>&2
+  echo "                                 element does not exist in arr." 1>&2
+  echo "  --remove-each arr element : removes each occurance of element within arr." 1>&2
+  echo "  --prepend arr element : places element at the beginning of arr" 1>&2
+  echo "  --append arr element : places element at the end of arr" 1>&2
+  echo "  --sort arr : performs a quick sort on the array" 1>&2
 }
 
 # Parses the user's input and decides a course of action:
 function parse_user_input() {
-    if [[ "$#" -eq 0 ]]; then
-        arrutils_usage
-        exit 1
-    fi
-    local user_option="$1"
-    shift
+  if [[ "$#" -eq 0 ]]; then
+    arrutils_usage
+    exit 1
+  fi
+  local user_option="$1"
+  shift
 
-    case "$user_option" in
-        --get-index-of)
-            get_index_of "$@"
-            ;;
-        --get-each-index-of)
-            get_each_index_of "$@"
-            ;;
-        --remove)
-            remove "$@"
-            ;;
-        --remove-each)
-            remove_each "$@"
-            ;;
-        --prepend)
-            prepend "$@"
-            ;;
-        --append)
-            append "$@"
-            ;;
-        --sort)
-            sort "$@"
-            ;;
-        *)
-            echoe "Unknown option ${RED}$user_option${NC}"
-            exit 2
-    esac
+  case "$user_option" in
+  --get-index-of)
+    get_index_of "$@"
+    ;;
+  --get-each-index-of)
+    get_each_index_of "$@"
+    ;;
+  --remove)
+    remove "$@"
+    ;;
+  --remove-each)
+    remove_each "$@"
+    ;;
+  --prepend)
+    prepend "$@"
+    ;;
+  --append)
+    append "$@"
+    ;;
+  --sort)
+    sort "$@"
+    ;;
+  *)
+    echoe "Unknown option ${RED}$user_option${NC}"
+    exit 2
+    ;;
+  esac
 }
 
 # Used for printing errors:
-function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+function echoe() { echo -e "${RED}ERROR${NC}: $@" 1>&2; }
 
 # Used for printing warnings:
-function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
+function echow() { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2; }
 
 ################################################################################
 ##                                                                            ##
@@ -99,90 +99,89 @@ function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
 # Syntax:
 #   get-index-of arr $element
 function get_index_of() {
-    if [[ "$#" -ne 2 ]]; then
-        echoe "Incorrect number of params passed to get-index-of"
-        return 1
+  if [[ "$#" -ne 2 ]]; then
+    echoe "Incorrect number of params passed to get-index-of"
+    return 1
+  fi
+  local arr_copy=$1[@]
+  local element="$2"
+  local ind=0
+  for e in "${arr_copy[@]}"; do
+    if [[ "$e" == "$element" ]]; then
+      echo $ind
+      return 0
+    else
+      ((ind += 1))
     fi
-    local arr_copy=$1[@]
-    local element="$2"
-    local ind=0
-    for e in "${arr_copy[@]}"; do
-        if [[ "$e" == "$element" ]]; then
-            echo $ind
-            return 0
-        else
-            ((ind+=1))
-        fi
-    done
-    echo -1
+  done
+  echo -1
 }
 
 function get_each_index_of() {
-    if [[ "$#" -ne 2 ]]; then
-        echoe "Incorrect number of params passed to get-each-index-of"
-        return 1
+  if [[ "$#" -ne 2 ]]; then
+    echoe "Incorrect number of params passed to get-each-index-of"
+    return 1
+  fi
+  local arr_copy=$1[@]
+  local element="$2"
+  local ind=0
+  local index_arr=()
+  for e in "${arr_copy[@]}"; do
+    if [[ "$e" == "$element" ]]; then
+      index_arr+=($ind)
     fi
-    local arr_copy=$1[@]
-    local element="$2"
-    local ind=0
-    local index_arr=()
-    for e in "${arr_copy[@]}"; do
-        if [[ "$e" == "$element" ]]; then
-            index_arr+=($ind)
-        fi
-        ((ind+=1))
-    done
-    echo "${index_arr[@]}"
+    ((ind += 1))
+  done
+  echo "${index_arr[@]}"
 }
 
 # Removes the first occurance of an element from a specified array
 function remove() {
-    if [[ "$#" -ne 2 ]]; then
-        echoe "Incorrect number of params passed to remove"
-        return 1
-    fi
-    local arr_copy=$1[@]
-    local element="$2"
-    local ind="$(get-index-of arr_copy "$element")"
-    if [[ "$ind" -ne -1 ]]; then
-        arr_copy=(${arr_copy[@]:0:$ind} ${arr_copy[@]:$(($ind + 1))})
-    fi
-    echo "${arr_copy[@]}"
+  if [[ "$#" -ne 2 ]]; then
+    echoe "Incorrect number of params passed to remove"
+    return 1
+  fi
+  local arr_copy=$1[@]
+  local element="$2"
+  local ind="$(get-index-of arr_copy "$element")"
+  if [[ "$ind" -ne -1 ]]; then
+    arr_copy=(${arr_copy[@]:0:$ind} ${arr_copy[@]:$(($ind + 1))})
+  fi
+  echo "${arr_copy[@]}"
 }
 
 # Removes all occurances of a specified element within a specified array
 function remove_each() {
-    if [[ "$#" -ne 2 ]]; then
-        echoe "Incorrect number of params passed to remove-each"
-        return 1
-    fi
-    local arr_copy=$1[@]
-    local element="$2"
-    local indecies=($(get_each_index_of arr_copy "$element"))
-    if [[ "${#indecies[@]}" -ne 0 ]]; then
-        for ind in "${indecies[@]}"; do
-            arr_copy=(${arr_copy[@]:0:$ind} ${arr_copy[@]:$(($ind + 1))})
-        done
-    fi
-    echo "${arr_copy[@]}"
+  if [[ "$#" -ne 2 ]]; then
+    echoe "Incorrect number of params passed to remove-each"
+    return 1
+  fi
+  local arr_copy=$1[@]
+  local element="$2"
+  local indecies=($(get_each_index_of arr_copy "$element"))
+  if [[ "${#indecies[@]}" -ne 0 ]]; then
+    for ind in "${indecies[@]}"; do
+      arr_copy=(${arr_copy[@]:0:$ind} ${arr_copy[@]:$(($ind + 1))})
+    done
+  fi
+  echo "${arr_copy[@]}"
 }
 
 # Puts the specified element at the beginning of the array
 function prepend() {
-    local arr_copy=$1[@]
-    local element="$2"
-    arr_copy=("$element" "${arr_copy[@]}")
-    echo "${arr_copy[@]}"
+  local arr_copy=$1[@]
+  local element="$2"
+  arr_copy=("$element" "${arr_copy[@]}")
+  echo "${arr_copy[@]}"
 }
 
 # Puts the specified element at the end of the array
 function append() {
-    local arr_copy=$1[@]
-    local element="$2"
-    arr_copy=("${arr_copy[@]}" "$element")
-    echo "${arr_copy[@]}"
+  local arr_copy=$1[@]
+  local element="$2"
+  arr_copy=("${arr_copy[@]}" "$element")
+  echo "${arr_copy[@]}"
 }
-
 
 ################################################################################
 ##                                                                            ##
@@ -194,51 +193,51 @@ function append() {
 # Syntax:
 #   sort arr_name
 function sort() {
-    local arr_copy=$1[@]
-    local left=0
-    local right=$((${#arr_copy[@]} - 1))
-    _quick_sort "$@"
+  local arr_copy=$1[@]
+  local left=0
+  local right=$((${#arr_copy[@]} - 1))
+  _quick_sort "$@"
 }
 
 # The actual sorting function:
 function _quick_sort() {
-    local arr_copy=$1[@]
-    local left="$2"
-    local right"$3"
-    local index="$(_partition arr_copy $left $right)"
-    if [[ "$left" -lt $((index - 1)) ]]; then
-        _quick_sort arr_copy $left $((index - 1))
-    fi
-    if [[ "$index" -lt $right ]]; then
-        _quick_sort arr_copy $index $right
-    fi
+  local arr_copy=$1[@]
+  local left="$2"
+  local right"$3"
+  local index="$(_partition arr_copy $left $right)"
+  if [[ "$left" -lt $((index - 1)) ]]; then
+    _quick_sort arr_copy $left $((index - 1))
+  fi
+  if [[ "$index" -lt $right ]]; then
+    _quick_sort arr_copy $index $right
+  fi
 }
 
 # Private method for partitioning the array for sorting purposes
 function _partition() {
-    local arr_copy=$1[@]
-    local i="$2"
-    local j="$3"
-    local tmp=0
-    local pivot=$(( ($i + $j) / 2 ))
+  local arr_copy=$1[@]
+  local i="$2"
+  local j="$3"
+  local tmp=0
+  local pivot=$((($i + $j) / 2))
 
-    while [[ $i -le $j ]]; do
-        while [[ ${arr_copy[$i]} -lt $pivot ]]; do
-            ((i+=1))
-        done
-        while [[ ${arr_copy[$j]} -gt $pivot ]]; do
-            ((j-=1))
-        done
-        if [[ $i -le $j ]]; then
-            tmp=${arr_copy[$i]}
-            arr_copy[$i]=${arr_copy[$j]}
-            arr_copy[$j]=$tmp
-            ((i+=1))
-            ((j-=1))
-        fi
+  while [[ $i -le $j ]]; do
+    while [[ ${arr_copy[$i]} -lt $pivot ]]; do
+      ((i += 1))
     done
+    while [[ ${arr_copy[$j]} -gt $pivot ]]; do
+      ((j -= 1))
+    done
+    if [[ $i -le $j ]]; then
+      tmp=${arr_copy[$i]}
+      arr_copy[$i]=${arr_copy[$j]}
+      arr_copy[$j]=$tmp
+      ((i += 1))
+      ((j -= 1))
+    fi
+  done
 
-    echo "$i"
+  echo "$i"
 }
 
 ################################################################################
@@ -247,8 +246,6 @@ function _partition() {
 ##                                                                            ##
 ################################################################################
 
-
-
 ################################################################################
 ##                                                                            ##
 ##                                 Main Program                               ##
@@ -256,5 +253,3 @@ function _partition() {
 ################################################################################
 
 parse_user_input "$@"
-
-
diff --git a/shell/bash/bin/fr b/shell/bash/bin/fr
--- a/shell/bash/bin/fr
+++ b/shell/bash/bin/fr
@@ -8,38 +8,37 @@
 
 # Full help message
 function fr_help() {
-    echo "fr is a find/replace tool that uses a combination of find and sed in order" 1>&2
-    echo "to replace string patterns with new ones in files." 1>&2
-    fr_usage
+  echo "fr is a find/replace tool that uses a combination of find and sed in order" 1>&2
+  echo "to replace string patterns with new ones in files." 1>&2
+  fr_usage
 }
 
 # Usage message
 function fr_usage() {
-    echo "Usage:" 1>&2
-    echo "    fr [options] [search pattern] [replace pattern]" 1>&2
-    echo "Options:" 1>&2
-    echo "    --dir | -d <directory path> " 1>&2
-    echo "        the base directory to search in" 1>&2
-    echo "    --file-pattern | -f <pattern>" 1>&2
-    echo "        a file pattern to narrow down search results" 1>&2
-    echo "    --search | -s <pattern>" 1>&2
-    echo "        the pattern to search for in the file heirarchy" 1>&2
-    echo "        (can also be entered as the first argument after all options)" 1>&2
-    echo "    --replace | -r <string>" 1>&2
-    echo "        the string to replace all matches with in the file heirarchy" 1>&2
-    echo "        (can also be entered as the second argument after all options)" 1>&2
-    echo "    --whole-word | -w" 1>&2
-    echo "        match whole words instead of a pattern" 1>&2
-    echo "    --non-recursive | -n" 1>&2
-    echo "        tell fr to only check the working directory for matches" 1>&2
-    echo "    --max-depth | -M <int>        " 1>&2
-    echo "        the maximum level of directories to recurse down when searching" 1>&2
-    echo "    --min-depth | -m <int>        " 1>&2
-    echo "        the minimum level of directories to recurse down when searching" 1>&2
-    echo "    --help | -h                   " 1>&2
-    echo "        print help message and exit" 1>&2
+  echo "Usage:" 1>&2
+  echo "    fr [options] [search pattern] [replace pattern]" 1>&2
+  echo "Options:" 1>&2
+  echo "    --dir | -d <directory path> " 1>&2
+  echo "        the base directory to search in" 1>&2
+  echo "    --file-pattern | -f <pattern>" 1>&2
+  echo "        a file pattern to narrow down search results" 1>&2
+  echo "    --search | -s <pattern>" 1>&2
+  echo "        the pattern to search for in the file heirarchy" 1>&2
+  echo "        (can also be entered as the first argument after all options)" 1>&2
+  echo "    --replace | -r <string>" 1>&2
+  echo "        the string to replace all matches with in the file heirarchy" 1>&2
+  echo "        (can also be entered as the second argument after all options)" 1>&2
+  echo "    --whole-word | -w" 1>&2
+  echo "        match whole words instead of a pattern" 1>&2
+  echo "    --non-recursive | -n" 1>&2
+  echo "        tell fr to only check the working directory for matches" 1>&2
+  echo "    --max-depth | -M <int>        " 1>&2
+  echo "        the maximum level of directories to recurse down when searching" 1>&2
+  echo "    --min-depth | -m <int>        " 1>&2
+  echo "        the minimum level of directories to recurse down when searching" 1>&2
+  echo "    --help | -h                   " 1>&2
+  echo "        print help message and exit" 1>&2
 }
-
 
 ################################################################################
 ##                                                                            ##
@@ -49,19 +48,19 @@ function fr_usage() {
 
 # Exit the program if the user requests help
 function exit_if_help_requested() {
-    if [[ "$1" == "--help" || "$1" == "-h" ]]; then
-        fr_help
-        exit 0
-    fi
+  if [[ "$1" == "--help" || "$1" == "-h" ]]; then
+    fr_help
+    exit 0
+  fi
 }
 
 # Exit program if user doesn't supply correct input
 function exit_if_input_incorrect() {
-    if [[ "$search" == "" || "$replace" == "" ]]; then
-        echoe "You must supply a search pattern and a replace string"
-        fr_usage
-        exit 1
-    fi
+  if [[ "$search" == "" || "$replace" == "" ]]; then
+    echoe "You must supply a search pattern and a replace string"
+    fr_usage
+    exit 1
+  fi
 }
 
 ################################################################################
@@ -70,12 +69,11 @@ function exit_if_input_incorrect() {
 ##                                                                            ##
 ################################################################################
 
-
 # Used for printing errors:
-function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+function echoe() { echo -e "${RED}ERROR${NC}: $@" 1>&2; }
 
 # Used for printing warnings:
-function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
+function echow() { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2; }
 
 ################################################################################
 ##                                                                            ##
@@ -101,61 +99,62 @@ find_args=""
 
 # Parse user input:
 for arg in "$@"; do
-    case "$arg" in
-        --dir | -d)
-            dir_path="$2"
-            shift 2
-            ;;
-        --file-pattern | -f)
-            file_pattern="-iname \"$2\""
-            shift 2
-            ;;
-        --search | -s)
-            search="$2"
-            shift 2
-            ;;
-        --replace | -r)
-            replace="$2"
-            shift 2
-            ;;
-        --whole-word | -w)
-            whole_word=true
-            shift 1
-            ;;
-        --non-recursive | -n)
-            max_depth="-maxdepth 1"
-            min_depth=""
-            shift 1
-            ;;
-        --max-depth | -M)
-            max_depth="-maxdepth $2"
-            shift 2
-            ;;
-        --min-depth | -m)
-            min_depth="-mindepth $2"
-            shift 2
-            ;;
-        --* | -*)
-            echoe "Unknown argument '$arg' to fr"
-            fr_usage
-            exit 2
-    esac
+  case "$arg" in
+  --dir | -d)
+    dir_path="$2"
+    shift 2
+    ;;
+  --file-pattern | -f)
+    file_pattern="-iname \"$2\""
+    shift 2
+    ;;
+  --search | -s)
+    search="$2"
+    shift 2
+    ;;
+  --replace | -r)
+    replace="$2"
+    shift 2
+    ;;
+  --whole-word | -w)
+    whole_word=true
+    shift 1
+    ;;
+  --non-recursive | -n)
+    max_depth="-maxdepth 1"
+    min_depth=""
+    shift 1
+    ;;
+  --max-depth | -M)
+    max_depth="-maxdepth $2"
+    shift 2
+    ;;
+  --min-depth | -m)
+    min_depth="-mindepth $2"
+    shift 2
+    ;;
+  --* | -*)
+    echoe "Unknown argument '$arg' to fr"
+    fr_usage
+    exit 2
+    ;;
+  esac
 done
 
 # If the user enters the find and replace strings as regular arguments,
 # parse them here:
 if [[ "$1" != "" ]]; then
-    search="$1"
-    shift 1
+  search="$1"
+  shift 1
 fi
 if [[ "$1" != "" ]]; then
-    replace="$1"
-    shift 1
+  replace="$1"
+  shift 1
 fi
 
 # Match whole words if the user specifies:
-if $whole_word ; then
-    search="\<$search\>"
+if $whole_word; then
+  search="\<$search\>"
 fi
 
 # Exit conditions:
@@ -165,9 +164,9 @@ exit_if_input_incorrect
 # Put the find arguments together to be evaluated:
 find_args="$dir_path -type f"
 for param in "$file_pattern" "$max_depth" "$min_depth"; do
-    if [[ "$param" != "" ]]; then
-        find_args="$find_args $param"
-    fi
+  if [[ "$param" != "" ]]; then
+    find_args="$find_args $param"
+  fi
 done
 find_args="$find_args -print0"
 
diff --git a/shell/bash/bin/nav b/shell/bash/bin/nav
--- a/shell/bash/bin/nav
+++ b/shell/bash/bin/nav
@@ -8,22 +8,22 @@
 
 # Full help message:
 function nav_help() {
-    echo "nav presents the user with a rectangular grid of directories in the current directory" 1>&2
-    echo "to which they can navigate. The user can use the arrow keys to select the directory" 1>&2
-    echo "they want, press 'd' to finish selecting, or press 'q' to cancel out of the menu. " 1>&2
-    echo "Once they make a selection, they will then see all directories in the previously selected" 1>&2
-    echo "directory and can make another selection." 1>&2
+  echo "nav presents the user with a rectangular grid of directories in the current directory" 1>&2
+  echo "to which they can navigate. The user can use the arrow keys to select the directory" 1>&2
+  echo "they want, press 'd' to finish selecting, or press 'q' to cancel out of the menu. " 1>&2
+  echo "Once they make a selection, they will then see all directories in the previously selected" 1>&2
+  echo "directory and can make another selection." 1>&2
 }
 
 # Usage message:
 function nav_usage() {
-    echo "Usage:" 1>&2
-    echo "     nav [-s|--show-hidden]" 1>&2
-    echo "Options:" 1>&2
-    echo "    -s | --show-hidden:" 1>&2
-    echo "Display all directories in the present dir, including hidden ones." 1>&2
-    echo "    -h | --help:" 1>&2
-    echo "Print the usage message." 1>&2
+  echo "Usage:" 1>&2
+  echo "     nav [-s|--show-hidden]" 1>&2
+  echo "Options:" 1>&2
+  echo "    -s | --show-hidden:" 1>&2
+  echo "Display all directories in the present dir, including hidden ones." 1>&2
+  echo "    -h | --help:" 1>&2
+  echo "Print the usage message." 1>&2
 }
 
 ################################################################################
@@ -33,11 +33,11 @@ function nav_usage() {
 ################################################################################
 
 # Exit the program if the user requests the help message:
-function exit_if_help_requested () {
-    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-        nav_help
-        exit 0
-    fi
+function exit_if_help_requested() {
+  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+    nav_help
+    exit 0
+  fi
 }
 
 ################################################################################
@@ -48,36 +48,39 @@ function exit_if_help_requested () {
 
 # Parse user input and get options:
 function get_options() {
-    # read the options
-    local args=$(getopt -o s --long show-hidden -n 'nav' -- "$@")
-    eval set -- "$args"
+  # read the options
+  local args=$(getopt -o s --long show-hidden -n 'nav' -- "$@")
+  eval set -- "$args"
 
-    # extract options and their arguments into variables.
-    while true ; do
-        case "$1" in
-            -s | --show-hidden)
-                shift
-                show_hidden=true
-                ;;
-            -h | --help)
-                shift
-                nav_help
-                break
-                ;;
-            --) shift ; break ;;
-            *)
-                echoe "Unknown option $1 to nav"
-                exit 2
-                ;;
-        esac
-    done
+  # extract options and their arguments into variables.
+  while true; do
+    case "$1" in
+    -s | --show-hidden)
+      shift
+      show_hidden=true
+      ;;
+    -h | --help)
+      shift
+      nav_help
+      break
+      ;;
+    --)
+      shift
+      break
+      ;;
+    *)
+      echoe "Unknown option $1 to nav"
+      exit 2
+      ;;
+    esac
+  done
 }
 
 # Used for printing errors:
-function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+function echoe() { echo -e "${RED}ERROR${NC}: $@" 1>&2; }
 
 # Used for printing warnings:
-function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
+function echow() { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2; }
 
 ################################################################################
 ##                                                                            ##
@@ -87,18 +90,18 @@ function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
 
 # Test the get_options function by giving it all possible options:
 function test_get_options() {
-    echo "Variable values before:" 1>&2
-    echo "    show_hidden: $show_hidden" 1>&2
+  echo "Variable values before:" 1>&2
+  echo "    show_hidden: $show_hidden" 1>&2
 
-    get_options -s
+  get_options -s
 
-    echo -e "\nVariable values with short options:" 1>&2
-    echo "    show_hidden: $show_hidden" 1>&2
+  echo -e "\nVariable values with short options:" 1>&2
+  echo "    show_hidden: $show_hidden" 1>&2
 
-    get_options --show-hidden
+  get_options --show-hidden
 
-    echo -e "\nVariable values with long options:" 1>&2
-    echo "    show_hidden: $show_hidden" 1>&2
+  echo -e "\nVariable values with long options:" 1>&2
+  echo "    show_hidden: $show_hidden" 1>&2
 }
 
 ################################################################################
diff --git a/shell/bash/bin/trim b/shell/bash/bin/trim
--- a/shell/bash/bin/trim
+++ b/shell/bash/bin/trim
@@ -3,7 +3,6 @@
 # Trims trailing/beginning white space from a string. Can also trim characters
 # from the beginning or end of the string.
 
-
 ################################################################################
 ##                                                                            ##
 ##                           Supporting Functions                             ##
@@ -11,21 +10,20 @@
 ################################################################################
 
 function trim_usage() {
-    echo "Trims beginning/trailing white space from a string. Can also" 1>&2
-    echo "trim characters from the beginning or end of the string." 1>&2
-    echo "USAGE:" 1>&2
-    echo "trim [-b n -e n] FILE" 1>&2
-    echo "OPTIONS:" 1>&2
-    echo "  -b <number of chars to trim> : trims the FIRST n chars from the string" 1>&2
-    echo "  -e <number of chars to trim> : trims the LAST n chars from the string" 1>&2
+  echo "Trims beginning/trailing white space from a string. Can also" 1>&2
+  echo "trim characters from the beginning or end of the string." 1>&2
+  echo "USAGE:" 1>&2
+  echo "trim [-b n -e n] FILE" 1>&2
+  echo "OPTIONS:" 1>&2
+  echo "  -b <number of chars to trim> : trims the FIRST n chars from the string" 1>&2
+  echo "  -e <number of chars to trim> : trims the LAST n chars from the string" 1>&2
 }
 
 # Used for printing errors:
-function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+function echoe() { echo -e "${RED}ERROR${NC}: $@" 1>&2; }
 
 # Used for printing warnings:
-function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
-
+function echow() { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2; }
 
 ################################################################################
 ##                                                                            ##
@@ -37,7 +35,6 @@ num_chars_to_trim_from_front=0
 num_chars_to_trim_from_end=0
 trimmed_string=""
 
-
 ################################################################################
 ##                                                                            ##
 ##                                Main Program                                ##
@@ -45,44 +42,44 @@ trimmed_string=""
 ################################################################################
 
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-    trim_usage
-    exit 1
+  trim_usage
+  exit 1
 fi
 
 while getopts ":b:e:" o; do
-    case "${o}" in
-        b)
-            num_chars_to_trim_from_front="${OPTARG}"
-            ;;
-        e)
-            num_chars_to_trim_from_end="${OPTARG}"
-            ;;
-        *)
-            echoe "Unknown operand"
-            trim_usage
-            exit 1
-            ;;
-    esac
+  case "${o}" in
+  b)
+    num_chars_to_trim_from_front="${OPTARG}"
+    ;;
+  e)
+    num_chars_to_trim_from_end="${OPTARG}"
+    ;;
+  *)
+    echoe "Unknown operand"
+    trim_usage
+    exit 1
+    ;;
+  esac
 done
 shift $((OPTIND - 1))
 
 if [[ "$#" -ne 0 ]]; then
-    echo "$1" 1>&2
-    trimmed_string="$(echo "$1" | sed "s/^[ ]*//" | sed "s/[ ]*$//")"
+  echo "$1" 1>&2
+  trimmed_string="$(echo "$1" | sed "s/^[ ]*//" | sed "s/[ ]*$//")"
 
-    # Optionally trim chars from front of string:
-    if [[ "$num_chars_to_trim_from_front" -gt 0 ]]; then
-        trimmed_string="$(echo "$trimmed_string" | sed "s/^.{$num_chars_to_trim_from_front}//")"
-    fi
+  # Optionally trim chars from front of string:
+  if [[ "$num_chars_to_trim_from_front" -gt 0 ]]; then
+    trimmed_string="$(echo "$trimmed_string" | sed "s/^.{$num_chars_to_trim_from_front}//")"
+  fi
 
-    # Optionally trim chars from end of string:
-    if [[ "$num_chars_to_trim_from_end" -gt 0 ]]; then
-        trimmed_string="$(echo "$trimmed_string" | sed "s/.{$num_chars_to_trim_from_end}$//")"
-    fi
+  # Optionally trim chars from end of string:
+  if [[ "$num_chars_to_trim_from_end" -gt 0 ]]; then
+    trimmed_string="$(echo "$trimmed_string" | sed "s/.{$num_chars_to_trim_from_end}$//")"
+  fi
 
-    echo "$trimmed_string"
+  echo "$trimmed_string"
 else
-    echoe "No string provided"
-    trim_usage
-    exit 2
+  echoe "No string provided"
+  trim_usage
+  exit 2
 fi
