Update init_nerd_fonts script

diff --git a/init/init_nerd_fonts b/init/init_nerd_fonts
--- a/init/init_nerd_fonts
+++ b/init/init_nerd_fonts
@@ -1,22 +1,28 @@
 #!/usr/bin/env bash
 
+# Trap errors and print error message
+set -uo pipefail
+trap 's=$?; echo "$0: Error on line "${LINENO}": ${BASH_COMMAND}"; exit $s' ERR
+
 # Variables {{{
 declare DOTFILES_HOME="${HOME}/.dotfiles"
 declare NERD_FONTS_GIT_URL="https://github.com/ryanoasis/nerd-fonts.git"
 declare NERD_FONTS_DEST_DIR
 declare LOG_LEVEL=3
+declare WS
 # }}}
 
 # Imports {{{
-. "${DOTFILES_REPO}/shell/common/source/common.sh" && src
+. "${DOTFILES_HOME}/shell/common/source/common.sh" && src
 # }}}
 
 # Functions {{{
 
 # Setup logic for this script.
 setup() {
+  WS="${WS:-${HOME}/workspace}"
   # Set variables that could not be set before importing definitions.
-  NERD_FONTS_DEST_DIR="$WS/nerd-fonts"
+  NERD_FONTS_DEST_DIR="${WS}/nerd-fonts"
 }
 
 clone_nerd_fonts_repo() {
@@ -26,18 +32,18 @@ clone_nerd_fonts_repo() {
 install_nerd_fonts() {
   if [ -d "${NERD_FONTS_DEST_DIR}" ]; then
     (
-      cd "${NERD_FONTS_DEST_DIR}"
+      cd "${NERD_FONTS_DEST_DIR}" || exit 1
       ./install.sh
     )
   else
     err "Nerd fonts directory does not exist."
-    return 1
+    exit 2
   fi
 }
 
 main() {
   setup
-  log_info "Initializing Nerd Fonts"
+  print_header "Initializing Nerd Fonts"
   clone_nerd_fonts_repo
   install_nerd_fonts
   log_info "Done"
