Adding more functionality/modularity to newbranch

diff --git a/git/bin/newbranch b/git/bin/newbranch
--- a/git/bin/newbranch
+++ b/git/bin/newbranch
@@ -24,8 +24,34 @@ function newbranch_usage() {
     echo "                       is not provided, the upstream branch defaults to origin/master" 1>&2
     echo "    -b <branch name> : sets the value of the new branch name. If this argument" 1>&2
     echo "                       is ommitted, the user will be prompted to provide a names" 1>&2
+    echo "    -n               : signals that the local branch should not track a remote branch" 1>&2
     echo "    -h --help        : prints the help message (this message)" 1>&2
 }
+
+# Decides how to create the local branch based on user input:
+function create_local_branch() {
+    if [[ "$#" -ne 3 ]]; then
+        echoe "Incorrect number of arguments passed to create_local_branch"
+        exit 2
+    fi
+
+    local new_branch_name="$1"
+    local upstream="$2"
+    local track_upstream="$3"
+
+    if $track_upstream ; then
+        git checkout -b "$new_branch_name" --track "$upstream"
+    else
+        git checkout -b "$new_branch_name"
+    fi
+}
+
+# Used for printing errors:
+function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+
+# Used for printing warnings:
+function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
+
 
 ################################################################################
 ##                                                                            ##
@@ -35,7 +61,7 @@ function newbranch_usage() {
 
 upstream="origin/master"
 new_branch_name=""
-
+track_upstream=true
 
 ################################################################################
 ##                                                                            ##
@@ -50,7 +76,7 @@ if [[ "$1" == "--help" || "$1" == "-h" ]]; then
 fi
 
 # Get options:
-while getopts ":u:b:" o; do
+while getopts ":u:b:n" o; do
     case "${o}" in
         u)
             upstream="${OPTARG}"
@@ -58,7 +84,11 @@ while getopts ":u:b:" o; do
         b)
             new_branch_name="${OPTARG}"
             ;;
+        n)
+            track_upstream=false
+            ;;
         *)
+            echoe "Unknown operand $o"
             newbranch_usage
             exit 1
             ;;
@@ -74,4 +104,4 @@ if [[ -z "$new_branch_name" ]]; then
     done
 fi
 
-git checkout -b "$new_branch_name" --track "$upstream"
+create_local_branch "$new_branch_name" "$upstream" "$track_upstream"
