Beginning work on arrutils

diff --git a/bash/bin/arrutils b/bash/bin/arrutils
--- a/bash/bin/arrutils
+++ b/bash/bin/arrutils
@@ -13,8 +13,79 @@
 # Options:
 #   --remove-element <object>  : Removes the specified element from the array if
 #                                it exists within the array.
-#   --copy-array <arr1> <arr2> : Copies the elements of arr1 into a new array
-#                                arr2.
 #   --get-index-of <arr> <element> : Returns a set of integer indecies of a specified
 #                                    element within arr. Returns -1 if the element is not present.
 #
+
+################################################################################
+##                                                                            ##
+##                                  Variables                                 ##
+##                                                                            ##
+################################################################################
+
+
+################################################################################
+##                                                                            ##
+##                           Supporting Functions                             ##
+##                                                                            ##
+################################################################################
+
+# Used for printing errors:
+function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+
+# Used for printing warnings:
+function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
+
+################################################################################
+##                                                                            ##
+##                                Main Functions                              ##
+##                                                                            ##
+################################################################################
+
+# Gets the incex of the first occurance of an element in an array
+# Syntax:
+#   get-index-of arr $element
+function get-index-of() {
+    if [[ "$#" -ne 2 ]]; then
+        echoe "Incorrect number of params passed to get-index-of"
+        return 1
+    fi
+
+    local arr_copy=$1[@]
+    local elem="$2"
+    local ind=0
+
+    for e in "${arr_copy[@]}"; do
+        if [[ "$e" == "$elem" ]]; then
+            echo $ind
+            return 0
+        else
+            ((ind+=1))
+        fi
+    done
+
+    echo -1
+}
+
+# Removes the first occurance of an element from a specified array
+function remove-element() {
+    if [[ "$#" -ne 2 ]]; then
+        echoe "Incorrect number of params passed to remove-element"
+        return 1
+    fi
+    local arr_copy=$1[@]
+    local elem="$2"
+    local ind="$(get-index-of arr_copy "$elem")"
+    if [[ "$ind" -ne -1 ]]; then
+        arr_copy=(${arr_copy[@]:0:$ind} ${arr_copy[@]:$(($ind + 1))})
+    fi
+    echo "${arr_copy[@]}"
+}
+
+
+################################################################################
+##                                                                            ##
+##                                 Main Program                               ##
+##                                                                            ##
+################################################################################
+
