Small reorganization of calc

diff --git a/bash/bin/calc b/bash/bin/calc
--- a/bash/bin/calc
+++ b/bash/bin/calc
@@ -402,6 +402,18 @@ function parse_user_input() {
     done
 }
 
+# Used for printing errors:
+function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+
+# Used for printing warnings:
+function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
+
+################################################################################
+##                                                                            ##
+##                               Test Function                                ##
+##                                                                            ##
+################################################################################
+
 # Test the math functions by printing out some test calculations
 function test_math_funcs() {
     echo "10 + 5 = $(add 10 5)" 1>&2
@@ -431,12 +443,6 @@ function test_stack_funcs() {
     echo "This is the second thing we popped off: $elem1" 1>&2
     echo "Now the size of the stack is: $(stack_size test_stack)" 1>&2
 }
-
-# Used for printing errors:
-function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
-
-# Used for printing warnings:
-function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
 
 ################################################################################
 ##                                                                            ##
