Messing with apt and diralias binaries

diff --git a/bash/bin/diralias b/bash/bin/diralias
--- a/bash/bin/diralias
+++ b/bash/bin/diralias
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -e
+
 ################################################################################
 ##                                                                            ##
 ##                             Supporting Functions                           ##
@@ -28,6 +30,12 @@ function shortpath () {
         echo "$input_path"
     }
 }
+
+# Used for printing errors:
+function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+
+# Used for printing warnings:
+function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
 
 
 ################################################################################
