Stuff

diff --git a/bash/bin/swb b/bash/bin/swb
--- a/bash/bin/swb
+++ b/bash/bin/swb
@@ -25,10 +25,10 @@ function swb_usage() {
 }
 
 # Used for printing errors:
-function echoe () { echo "${RED}ERROR${NC}: $@" 1>&2 ; }
+function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
 
 # Used for printing warnings:
-function echow () { echo "${YELLOW}WARNING${NC}: $@" 1>&2 ; }
+function echow () { echo -e "${YELLOW}WARNING${NC}: $@" 1>&2 ; }
 
 ###########################################################################
 ##                                                                       ##
@@ -67,6 +67,6 @@ else
     if $color_flag; then
         echo -e "${RED}$(git rev-parse --abbrev-ref HEAD)${NC} is the only branch in this repository" 1>&2
     else
-        echo -e "$(git rev-parse --abbrev-ref HEAD) is the only branch in this repository" 1>&2
+        echo "$(git rev-parse --abbrev-ref HEAD) is the only branch in this repository" 1>&2
     fi
 fi
diff --git a/bash/bin/uprepo b/bash/bin/uprepo
--- a/bash/bin/uprepo
+++ b/bash/bin/uprepo
@@ -30,6 +30,12 @@ function uprepo_usage() {
     echo "  -a : specifies that the changes should be added to the previous commit" 1>&2
 }
 
+# Used for printing errors:
+function echoe () { echo -e "${RED}ERROR${NC}: $@" 1>&2 ; }
+
+# Used for printing warnings:
+function echow () { echo -e "${BROWN_ORANGE}WARNING${NC}: $@" 1>&2 ; }
+
 ###########################################################################
 ##                                                                       ##
 ##                             Main Program                              ##
@@ -43,7 +49,7 @@ fi
 
 git rev-parse --is-inside-work-tree >> /dev/null
 if [[ "$?" -ne 0 ]]; then
-    echo "Not a git repository" 1>&2
+    echoe "Not a git repository"
     echo "Aborting" 1>&2
     exit 1
 fi
@@ -75,7 +81,7 @@ done
 # Make sure there are files staged for commit. If not, ask user whether or
 # not to add all changed files to the commit:
 if [[ $(git diff --cached --numstat | wc -l | sed -e "s/[ \t]//g") -eq 0 ]]; then
-    echo "No files staged for commit." 1>&2
+    echow "No files staged for commit."
     response=""
     while [[ ! $response =~ [Yy] && ! $response =~ [Nn] ]]; do
         echo "Add all modified files in repo to commit? [y/n]" 1>&2
